# Generated by Django 5.0.1 on 2024-01-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_field",
                    models.CharField(help_text="請輸入陌生號碼", max_length=10, unique=True),
                ),
                ("number_owner", models.CharField(help_text="是誰來電？", max_length=30)),
                ("should_reject", models.BooleanField(help_text="是否該拒接")),
            ],
        ),
    ]
