# Generated by Django 5.0.1 on 2024-01-25 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_rename_number_field_number_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="number",
            options={"ordering": ["number", "owner", "is_scam"]},
        ),
        migrations.RenameField(
            model_name="number",
            old_name="should_reject",
            new_name="is_scam",
        ),
        migrations.RenameField(
            model_name="number",
            old_name="number_owner",
            new_name="owner",
        ),
    ]
